backend:
  name: github
  repo: anusree6154s/bits-and-bytes
  branch: main
  site_domain: anusree6154s.github.io/bits-and-bytes
  base_url: https://netlify-cms-github-oauth-bf5t.onrender.com
  auth_endpoint: /auth?site=https://anusree6154s.github.io/bits-and-bytes

media_folder: "assets/uploads"
public_folder: "/bits-and-bytes/assets/uploads"
# public_folder: "/assets/uploads"

collections:
  - name: "docs"
    label: "Docs"
    folder: "_docs"
    create: true
    format: frontmatter
    slug: "{{slug}}/"
    path: "{{slug}}/readme" # This is where CMS will write the file
    extension: "md"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "default" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Parent", name: "parent", widget: "string", required: false  }
      - { label: "Has Children", name: "has_children", widget: "boolean", default: false, required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pages"
    label: "Pages (old version)"
    folder: "content"
    create: true
    format: frontmatter
    slug: "{{slug}}/README"
    path: "{{slug}}/README"  # This is where CMS will write the file
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Excerpt", name: "excerpt", widget: "string", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

# local_backend: true # Add this line to debug locally, also run npx decap-server
